
name: 'yukon_shop'
version: '0.1'
profile: 'yukon_shop'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  yukon_shop:
      materialized: table
      staging:
        materialized: table
